#!/usr/bin/env python3

import subprocess
import sys
import urllib.request
import os

url = 'https://codeberg.org/paintgoblin/shugits/raw/commit/cadecff37713c5883d4a203f5063d54ffb3198c2/sbt-launch.jar'
destination = 'target/sbt-launch.jar'

def main():
    os.makedirs(os.path.dirname(destination), exist_ok=True)

    if not os.path.isfile(destination):
        download_file(url, destination)

    exit(
        subprocess.run(['java', '-jar', destination] + sys.argv[1:], check=False).returncode
    )

def download_file(url, destination):
    try:
        urllib.request.urlretrieve(url, destination)
        print(f"File downloaded successfully and saved as {destination}")
    except Exception as e:
        print(f"Failed to download file: {e}")

#!/usr/bin/env python3


if __name__ == '__main__':
    main()
